export const FIELD_OF_STUDY_SUGGESTIONS: string[] = [
  // Business
  "Accounting",
  "Actuarial Science",
  "Business Administration",
  "Business Analytics",
  "Economics",
  "Entrepreneurship",
  "Finance",
  "Human Resources Management",
  "International Business",
  "Management",
  "Management Information Systems",
  "Marketing",
  "Operations Management",
  "Real Estate",
  "Supply Chain Management",

  // Computing & Technology
  "Artificial Intelligence",
  "Bioinformatics",
  "Computer Engineering",
  "Computer Science",
  "Cybersecurity",
  "Data Science",
  "Game Design",
  "Human-Computer Interaction",
  "Information Systems",
  "Information Technology",
  "Machine Learning",
  "Software Engineering",
  "Web Development",

  // Engineering
  "Aerospace Engineering",
  "Agricultural Engineering",
  "Biomedical Engineering",
  "Chemical Engineering",
  "Civil Engineering",
  "Electrical Engineering",
  "Environmental Engineering",
  "Industrial Engineering",
  "Materials Science and Engineering",
  "Mechanical Engineering",
  "Mechatronics Engineering",
  "Nuclear Engineering",
  "Petroleum Engineering",
  "Robotics Engineering",
  "Structural Engineering",

  // Natural & Physical Sciences
  "Astronomy",
  "Astrophysics",
  "Atmospheric Science",
  "Biochemistry",
  "Biology",
  "Biotechnology",
  "Botany",
  "Chemistry",
  "Ecology",
  "Environmental Science",
  "Genetics",
  "Geology",
  "Marine Biology",
  "Microbiology",
  "Molecular Biology",
  "Neuroscience",
  "Oceanography",
  "Physics",
  "Zoology",

  // Mathematics & Statistics
  "Applied Mathematics",
  "Mathematics",
  "Statistics",

  // Health & Medicine
  "Athletic Training",
  "Dentistry",
  "Health Sciences",
  "Kinesiology",
  "Medicine",
  "Nursing",
  "Nutrition Science",
  "Occupational Therapy",
  "Optometry",
  "Pharmacy",
  "Physical Therapy",
  "Public Health",
  "Radiologic Technology",
  "Speech-Language Pathology",
  "Veterinary Medicine",

  // Social Sciences
  "Anthropology",
  "Archaeology",
  "Criminal Justice",
  "Geography",
  "International Relations",
  "Political Science",
  "Psychology",
  "Public Administration",
  "Public Policy",
  "Social Work",
  "Sociology",
  "Urban Planning",

  // Humanities
  "African American Studies",
  "American Studies",
  "Classics",
  "Comparative Literature",
  "English",
  "Ethnic Studies",
  "Gender Studies",
  "History",
  "Linguistics",
  "Philosophy",
  "Religious Studies",
  "Women's Studies",

  // Languages
  "Arabic",
  "Chinese",
  "French",
  "German",
  "Italian",
  "Japanese",
  "Korean",
  "Latin",
  "Portuguese",
  "Russian",
  "Spanish",

  // Arts, Design & Media
  "Animation",
  "Architecture",
  "Art History",
  "Creative Writing",
  "Dance",
  "Fashion Design",
  "Film Studies",
  "Fine Arts",
  "Graphic Design",
  "Industrial Design",
  "Interior Design",
  "Journalism",
  "Music",
  "Music Production",
  "Photography",
  "Studio Art",
  "Theater",

  // Communications
  "Advertising",
  "Communications",
  "Digital Media",
  "Media Studies",
  "Public Relations",

  // Education
  "Early Childhood Education",
  "Education",
  "Educational Psychology",
  "Elementary Education",
  "Secondary Education",
  "Special Education",

  // Law & Legal Studies
  "Law",
  "Legal Studies",
  "Paralegal Studies",

  // Agriculture & Environment
  "Agricultural Science",
  "Agronomy",
  "Animal Science",
  "Environmental Studies",
  "Forestry",
  "Horticulture",
  "Sustainability Studies",

  // Hospitality & Culinary
  "Culinary Arts",
  "Event Management",
  "Hospitality Management",
  "Tourism Management",

  // Other Professional Fields
  "Aviation",
  "Construction Management",
  "Fire Science",
  "Library Science",
  "Logistics",
  "Physical Education",
  "Religious Ministry",
  "Sports Management",
];
