export const ROLE_SUGGESTIONS: string[] = [
  "Software Engineer",
  "Frontend Engineer",
  "Backend Engineer",
  "Full Stack Engineer",
  "Mobile Engineer",
  "iOS Engineer",
  "Android Engineer",
  "Site Reliability Engineer",
  "DevOps Engineer",
  "Platform Engineer",
  "Infrastructure Engineer",
  "Cloud Engineer",
  "Security Engineer",
  "QA Engineer",
  "Test Automation Engineer",
  "Machine Learning Engineer",
  "AI Engineer",
  "Data Engineer",
  "Data Scientist",
  "Data Analyst",
  "Business Analyst",
  "Research Scientist",
  "Engineering Manager",
  "Technical Lead",
  "Staff Engineer",
  "Principal Engineer",
  "Solutions Architect",
  "Systems Architect",
  "Product Manager",
  "Technical Product Manager",
  "Program Manager",
  "Project Manager",
  "Product Designer",
  "UX Designer",
  "UI Designer",
  "UX Researcher",
  "Graphic Designer",
  "Growth Marketing Manager",
  "Marketing Manager",
  "Content Strategist",
  "Sales Engineer",
  "Solutions Engineer",
  "Customer Success Manager",
  "Technical Writer",
  "Developer Advocate",
  "Support Engineer",
  "Database Administrator",
  "Network Engineer",
  "Embedded Systems Engineer",
  "Game Developer",
  "Blockchain Engineer",
];
