export const SKILL_SUGGESTIONS: string[] = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C++",
  "C#",
  "Go",
  "Rust",
  "Ruby",
  "PHP",
  "Swift",
  "Kotlin",
  "SQL",
  "React",
  "Next.js",
  "Vue",
  "Angular",
  "Svelte",
  "Node.js",
  "Express",
  "Django",
  "Flask",
  "Spring Boot",
  "Ruby on Rails",
  "GraphQL",
  "REST APIs",
  "HTML",
  "CSS",
  "Tailwind CSS",
  "Redux",
  "AWS",
  "Google Cloud Platform",
  "Azure",
  "Docker",
  "Kubernetes",
  "Terraform",
  "CI/CD",
  "Git",
  "Linux",
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "Elasticsearch",
  "Kafka",
  "Spark",
  "Airflow",
  "Machine Learning",
  "Deep Learning",
  "Natural Language Processing",
  "Computer Vision",
  "PyTorch",
  "TensorFlow",
  "Data Analysis",
  "Data Visualization",
  "Pandas",
  "NumPy",
  "A/B Testing",
  "Product Strategy",
  "Roadmapping",
  "User Research",
  "Wireframing",
  "Figma",
  "Sketch",
  "Design Systems",
  "Accessibility",
  "Agile",
  "Scrum",
  "Project Management",
  "Stakeholder Management",
  "Technical Writing",
  "Public Speaking",
  "Mentoring",
  "System Design",
  "Distributed Systems",
  "Microservices",
  "Security",
  "Penetration Testing",
  "Networking",
  "Mobile Development",
  "iOS Development",
  "Android Development",
  "React Native",
  "Flutter",
];
